"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext({
  lang: "kn",
  setLang: () => {},
  t: {},
});

const dashboardCopy = {
  en: {
    loginTitle: "MLA Office Login",
    loginSubtitle: "Kudligi Constituency digital portal",
    tabAdmin: "Admin",
    tabStaff: "Staff",
    email: "Email",
    password: "Password",
    phone: "Mobile number",
    role: "Role",
    sendOtp: "Send OTP",
    otp: "Enter OTP",
    verifyLogin: "Verify & Login",
    adminLogin: "Login",
    otpHint: "Demo OTP: 123456",
    comingSoon: "Coming soon",
    invalidCreds: "Invalid email or password",
    invalidPhone: "Enter a valid 10-digit mobile number",
    invalidOtp: "Invalid OTP",
    selectRole: "Select a role",
    roleNotEnabled: "This role is not available yet",
    backHome: "Back to website",
    dashboard: "Dashboard",
    development: "Development (Works)",
    departmentRecords: "Department Records",
    adminModDeptDesc: "Upload and organise secretariat, department, and follow-up letters.",
    openDepartmentRecords: "Open Department Records",
    manageAccess: "Manage Access",
    manageAccessDesc: "Choose a portal tab, see who already has access, then tick what they can do.",
    landingPage: "Landing Page",
    navLeaders: "Leaders",
    navTourSchedules: "Tour Program",
    tourPageTitle: "MLA Tour Program",
    addTourDay: "Add day",
    editTourDay: "Edit day schedule",
    tourDate: "Date",
    tourDayImage: "Daily schedule sheet",
    tourFallbackImage: "Default / fallback sheet",
    tourDateRequired: "Date is required",
    tourImageRequired: "Please upload a schedule image",
    tourDateExists: "This date already has a schedule. Use Edit on that day.",
    tourDraftSaved: "Saved in draft — click Sync to publish",
    tourSynced: "Synced to landing page",
    tourRemoveConfirm: "Remove this day's schedule from the public calendar?",
    tourNoDays: "No day schedules yet",
    tourDayHint: "Upload the schedule sheet image for this date.",
    tourPageDesc:
      "Upload or edit day-wise schedule sheets. Sync to show them on the public calendar.",
    tourCalendarHint:
      "Today and upcoming days: upload a schedule image. If a day already has a file, click to view it. Past empty days are locked.",
    tourHasFile: "Uploaded — click to view",
    tourToday: "Today",
    tourClickEmpty: "Click today or upcoming empty day to upload",
    tourViewDay: "Schedule for this day",
    tourUploadDay: "Upload schedule image",
    tourUploadOnlyHint:
      "Upload the schedule sheet image only. It publishes automatically.",
    tourUploadPublish: "Upload & publish",
    tourUsesRecent: "Uses latest sheet (no new upload)",
    tourPastNoUpload: "Upload is only allowed for today and upcoming days",
    tourUploadFromToday: "Upload allowed: today & upcoming days only",
    remove: "Remove",
    addLeader: "Add leader",
    editLeader: "Edit leader",
    leaderNameRequired: "Name is required",
    leaderPhoneRequired: "Phone or WhatsApp number is required",
    landingPageDesc:
      "Use the tabs to edit Brand, Header, Hero and more. Preview stays in the side panel.",
    landingEditModule: "Editing module",
    landingSidePreview: "Side preview",
    landingSave: "Save changes",
    landingSync: "Sync to landing",
    landingSynced: "Synced to landing page",
    landingReset: "Reset to defaults",
    landingResetDone: "Reset to defaults",
    landingOpen: "Open landing",
    landingOpenPreview: "Open preview",
    landingPreviewOpened: "Preview opened — showing synced content",
    landingShowPreview: "Show preview",
    landingHidePreview: "Hide preview",
    landingPreviewHint:
      "Small live look while you edit tabs. Sync to update the real landing page.",
    landingSaved: "Landing page saved",
    landingResetConfirm:
      "Reset all landing content to defaults? This cannot be undone.",
    adminSidebarTitle: "Admin panel",
    adminSidebarHint: "All modules · one place",
    sidebarCollapse: "Collapse menu",
    sidebarExpand: "Open menu",
    navDemands: "Demands",
    navComplaints: "Complaints",
    complaintsPageDesc: "Public landing complaint submissions inbox",
    navAssembly: "Assembly Q&A",
    accessStaffList: "Staff users",
    accessAddStaff: "Add staff",
    accessNoStaff: "No staff yet. Add one.",
    accessNameEn: "Name (EN)",
    accessNameKn: "Name (KN)",
    accessNameMain: "Name",
    accessNameKnOptional: "Kannada name (optional)",
    accessNameLangHint:
      "Name is used in English and Kannada. Fill Kannada only if you want a different Kannada spelling.",
    accessFillKannada: "Fill Kannada from name",
    accessNeedOnePerm: "Tick at least one permission before saving.",
    accessUsersOnPortal: "Users with access",
    accessNoUsersOnPortal: "No users on this portal yet. Add staff above.",
    accessAddToPortalHint: "Add a user to this portal (View is turned on by default).",
    accessAddToPortal: "Add to this portal",
    accessStaffCol: "Staff",
    accessRemoveFromPortal: "Remove from this portal?",
    accessRemovedFromPortal: "Removed from this portal.",
    accessStaffAdded: "Staff added to this portal.",
    accessProfileSaved: "Name and phone updated.",
    accessPhoneTaken: "That mobile number is already used by another staff.",
    accessNameRequired: "Enter a name.",
    accessPortalRights: "Set permissions",
    accessToggleHint: "Tick a box to allow that action.",
    accessSummaryTitle: "Currently granted",
    accessAllowed: "Allowed",
    accessDenied: "Off",
    accessNoneGranted: "No access yet",
    accessNoPortalAccess: "No access to this portal",
    accessGiveAll: "Give all",
    accessClearAll: "Clear all",
    accessSaved: "Access saved.",
    accessDeleted: "Staff removed.",
    accessConfirmDelete: "Remove this staff access record?",
    accessInvalidPhone: "Enter a valid 10-digit mobile number",
    deptUpload: "Upload files",
    deptUploadHint: "PDF, images, or documents — max 2.5 MB each",
    deptTitleOptional: "Title (optional)",
    deptTitlePlaceholder: "Short label for this file",
    deptEmpty: "No documents in this category yet. Upload one.",
    deptConfirmDelete: "Archive this document? It will be hidden, not permanently deleted.",
    archive: "Archive",
    archiveConfirm: "Archive this record? It will be hidden, not permanently deleted.",
    actions: "Actions",
    deptOpen: "Open",
    deptFileTooLarge: "File is too large (max 2.5 MB).",
    deptUploadFailed: "Could not read that file. Try another.",
    deptUploaded: "Uploaded",
    deptSelectFiles: "Choose files",
    deptUploading: "Uploading…",
    deptDropHere: "Drop files here",
    deptDropOrClick: "or click to browse",
    deptDragging: "Release to upload",
    deptSearchPlaceholder: "Search by title, file name, category…",
    deptSearchHint: "Type to search all department documents…",
    deptStatus: "Status",
    deptEGeneratedId: "E-Generated ID",
    deptEGeneratedIdPlaceholder: "Enter e-generated ID",
    deptEGeneratedIdRequired: "E-Generated ID is required for follow ups.",
    logout: "Logout",
    themeToggle: "Toggle dark / light theme",
    themeLight: "Switch to light theme",
    themeDark: "Switch to dark theme",
    logoutConfirmTitle: "Log out?",
    logoutConfirmMessage: "Are you sure you want to log out of the portal?",
    logoutConfirmYes: "Yes, log out",
    logoutConfirmNo: "Stay logged in",
    welcome: "Welcome",
    adminHomeTitle: "Admin Dashboard",
    adminHomeDesc: "Full office overview — works, documents and staff access. Use the sidebar to open modules.",
    adminModules: "Office modules",
    adminChartsSection: "Analytics",
    adminChartNoData: "No data for this year",
    adminChartInteractiveHint: "Six analytics views · 2 per row · each has its own year filter.",
    adminChartYear: "Year",
    adminChartAllYears: "All years",
    adminChartTitleWorksByGp: "Works by Gram Panchayat",
    adminChartHintWorksByGp: "How many works are running in each GP.",
    adminChartTitleStatus: "Works by status",
    adminChartHintStatus: "Share of ongoing vs completed works.",
    adminChartTitleAmountTrend: "Sanction amount over time",
    adminChartHintAmountTrend: "Month-wise sanctioned amount trend.",
    adminChartTitleByYojane: "Amount by scheme",
    adminChartHintByYojane: "Which yojane / scheme got more funds.",
    adminChartTitleProgress: "Progress over months",
    adminChartHintProgress: "Ongoing and completed works stacked by month.",
    adminChartTitleCombo: "Works count & amount",
    adminChartHintCombo: "Bars = number of works · line = sanctioned amount.",
    adminChartTypeColumn: "Column",
    adminChartTypePie: "Pie",
    adminChartTypeLine: "Line",
    adminChartTypeBar: "Bar",
    adminChartTypeArea: "Area",
    adminChartTypeCombo: "Column + Line",
    adminStatDocs: "Documents",
    adminStatStaff: "Staff users",
    adminStatPopulation: "Total population",
    adminStatGps: "Gram Panchayats",
    adminStatVillages: "Villages",
    adminModDevDesc: "Track Gram Panchayat works, amounts, photos and reports.",
    openDevelopment: "Open Development",
    gp: "Gram Panchayat",
    village: "Village",
    selectGp: "Select Gram Panchayat",
    selectVillage: "Select Village",
    addRecord: "Add development",
    editRecord: "Edit development",
    colName: "Development name",
    colAmount: "Amount sanctioned",
    colImages: "Development images",
    colYojane: "Yojane / Scheme",
    colDescription: "Description",
    colActions: "Actions",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirmDelete: "Archive this development record? It will be hidden, not permanently deleted.",
    noRows: "No developments for this village yet. Add one.",
    noRowsFiltered: "No works match these filters. Try another status or clear filters.",
    pickFilters: "Select Gram Panchayat and Village to view records.",
    pickVillageHint: "Select a village to see works for this Gram Panchayat.",
    clearFilters: "Clear filters",
    filterStatus: "Status",
    filterStatusAll: "All statuses",
    sortBy: "Sort by",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    sortAmountHigh: "Amount — high to low",
    sortAmountLow: "Amount — low to high",
    sortName: "Name A–Z",
    emptyAddCta: "Add first work",
    namePlaceholder: "e.g. Road repair",
    amountPlaceholder: "Amount in INR",
    yojanePlaceholder: "e.g. MGNREGA",
    descriptionPlaceholder: "Short description of this development work",
    uploadImages: "Upload photos & videos",
    uploadMediaHint: "You can add one or more photos and videos",
    removeImage: "Remove",
    mediaPhotos: "Photos",
    mediaVideos: "Videos",
    colMedia: "Photos & videos",
    videoLabel: "Video",
    quickLinks: "Quick links",
    download: "Download",
    downloadTitle: "Download developments",
    downloadScope: "What to download",
    downloadFormat: "File format",
    downloadNow: "Download now",
    scopeAll: "All developments",
    scopeGp: "One Gram Panchayat",
    scopeVillage: "One village",
    searchPlaceholder: "Search by name, yojane, description…",
    searchNoResults: "No developments match your search.",
    search: "Search",
    searchHint: "Type to search all development works…",
    voiceTapToSpeak: "Tap to speak",
    voiceListening: "Listening… tap to stop",
    voiceListeningShort: "Listening…",
    voiceUnsupported: "Voice search not supported in this browser",
    voiceMicDenied: "Microphone permission is needed for voice search",
    voiceMicDeniedTitle: "Turn on microphone",
    voiceMicDeniedBody:
      "This browser has blocked the microphone. Please allow mic access for this site, then tap the mic again.",
    voiceMicMissingTitle: "No microphone found",
    voiceMicMissingBody:
      "Connect a microphone (or enable it in system settings), then try again.",
    voiceMicStep1: "Click the lock / site info icon near the address bar",
    voiceMicStep2: "Set Microphone to Allow",
    voiceMicStep3: "Reload the page and tap the mic again",
    voiceMicGotIt: "Got it",
    voiceUseChrome: "Please use Chrome or Edge for voice search.",
    globalSearchPlaceholder: "Search works, documents…",
    globalSearchHint: "Search across modules you can access…",
    previewTitle: "Preview",
    previewSummary: "Summary",
    previewRecords: "records",
    previewEmpty: "Select scope to preview records here.",
    dateRange: "Date range",
    dateFrom: "From",
    dateTo: "To",
    dateHint: "Optional — filters by work start date",
    chartsTitle: "Overview",
    chartTotalWorks: "Total works",
    chartTotalAmount: "Total amount",
    chartOngoing: "Ongoing",
    chartCompleted: "Completed",
    chartByStatus: "Works by status",
    chartByYojane: "Amount by yojane",
    chartPieStatus: "Status pie chart",
    chartBarYojane: "Bar chart — amount by yojane",
    chartLineTrend: "Line chart — sanction trend",
    chartLineHint: "Based on work start month",
    chartBarCount: "Bar chart — works count by yojane",
    close: "Close",
    viewDetails: "Tap to view details",
    detailsTitle: "Development details",
    colStatus: "Status",
    colBeneficiaries: "Beneficiaries",
    colDepartment: "Department",
    colStartDate: "Start date",
    colLocation: "Location",
    colMoreDetails: "Work details",
    gpLabel: "Gram Panchayat",
    villageLabel: "Village",
    bedkePageDesc: "Select a Gram Panchayat and village to view or add needs (Bedke).",
    bedkePickGpHint: "Select a Gram Panchayat and village to see existing needs.",
    bedkeTabCivil: "Civil approach",
    bedkeTabPersonal: "Personal approach",
    bedkeNoNeeds: "No needs for this village in this tab.",
    bedkeAdd: "Add Bedke",
    bedkeName: "Name",
    bedkeNamePlaceholder: "Enter full name",
    bedkeNameRequired: "Enter a name.",
    bedkeApproach: "Approach",
    bedkeSubject: "Subject",
    bedkeSubjectPlaceholder: "Describe the need / request",
    bedkeSubjectRequired: "Enter a subject.",
    bedkeSelectVillageFirst: "Select Gram Panchayat and village first.",
    bedkeStatus: "Status",
    bedkePending: "Pending",
    bedkeInProgress: "In progress",
    bedkeCompleted: "Completed",
    bedkeRejected: "Rejected",
    bedkeEdit: "Edit demand",
    bedkeConfirmSave: "Confirm & save",
    bedkeDate: "Date",
    bedkePreview: "Preview",
    bedkePreviewTitle: "Preview Bedke",
    bedkePreviewHint: "Check the details below, then confirm to save.",
    bedkeBackEdit: "Back to edit",
    bedkeConfirmSubmit: "Confirm & submit",
    bedkeSearchPlaceholder: "Search by name, subject, GP, village…",
    bedkeSearchHint: "Type to search all Bedke / demands…",
    bedkeSearchNoResults: "No demands match your search.",
    bedkeDownloadTitle: "Download demands",
    aqPageDesc:
      "Track assembly questions asked by the MLA or other parties, answers, and uploaded reply files.",
    aqTabAll: "All",
    aqTabMla: "Asked by MLA",
    aqTabOther: "Asked by others",
    aqAdd: "Add Q&A",
    aqFormHint: "Enter the question, who asked it, answer (if ready), and attach files.",
    aqQuestionNo: "Question no.",
    aqSessionDate: "Session date",
    aqSessionLabel: "Session",
    aqSessionPlaceholder: "e.g. Monsoon Session 2026",
    aqAskedBy: "Asked by",
    aqAskedByName: "Name",
    aqAskedByNamePlaceholder: "Name of the member who asked",
    aqAskedByNameRequired: "Enter the name of who asked.",
    aqParty: "Party",
    aqPartyPlaceholder: "Party / group name",
    aqPartyRequired: "Enter the party name.",
    aqQuestion: "Question",
    aqQuestionPlaceholder: "Type the assembly question…",
    aqQuestionRequired: "Enter the question.",
    aqAnswer: "Answer",
    aqAnswerPlaceholder: "Type the answer / department reply (optional)…",
    aqNoAnswerYet: "No answer uploaded yet.",
    aqStatus: "Status",
    aqStatusPending: "Pending",
    aqStatusAnswered: "Answered",
    aqAttachFiles: "Attach files",
    aqFiles: "files",
    aqNoFiles: "No files attached.",
    aqView: "View",
    aqSave: "Save Q&A",
    aqEmpty: "No assembly Q&A in this tab yet. Add one.",
    aqRecords: "records",
    aqConfirmDelete: "Archive this assembly Q&A record? It will be hidden, not permanently deleted.",
    aqSearchPlaceholder: "Search by question, answer, name, party…",
    aqSearchHint: "Type to search all assembly Q&A…",
    aqSearchNoResults: "No assembly Q&A match your search.",
  },
  kn: {
    loginTitle: "ಶಾಸಕರ ಕಚೇರಿ ಲಾಗಿನ್",
    loginSubtitle: "ಕೂಡ್ಲಿಗಿ ಕ್ಷೇತ್ರ ಡಿಜಿಟಲ್ ಪೋರ್ಟಲ್",
    tabAdmin: "ನಿರ್ವಾಹಕ",
    tabStaff: "ಸಿಬ್ಬಂದಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    role: "ಪಾತ್ರ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    otp: "OTP ನಮೂದಿಸಿ",
    verifyLogin: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್",
    adminLogin: "ಲಾಗಿನ್",
    otpHint: "ಡೆಮೋ OTP: 123456",
    comingSoon: "ಶೀಘ್ರದಲ್ಲೇ",
    invalidCreds: "ತಪ್ಪಾದ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್",
    invalidPhone: "ಮಾನ್ಯವಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ನಮೂದಿಸಿ",
    invalidOtp: "ತಪ್ಪಾದ OTP",
    selectRole: "ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    roleNotEnabled: "ಈ ಪಾತ್ರ ಇನ್ನೂ ಲಭ್ಯವಿಲ್ಲ",
    backHome: "ವೆಬ್‌ಸೈಟ್‌ಗೆ ಹಿಂದಿರುಗಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    development: "ಕಾಮಗಾರಿಗಳು",
    departmentRecords: "ಇಲಾಖಾ ದಾಖಲೆಗಳು",
    adminModDeptDesc: "ಸಚಿವಾಲಯ, ಇಲಾಖಾ ಮತ್ತು ಅನುಸರಣೆ ಪತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮತ್ತು ವರ್ಗೀಕರಿಸಿ.",
    openDepartmentRecords: "ಇಲಾಖಾ ದಾಖಲೆಗಳು ತೆರೆಯಿರಿ",
    manageAccess: "ಪ್ರವೇಶ ನಿರ್ವಹಣೆ",
    manageAccessDesc: "ಪೋರ್ಟಲ್ ಟ್ಯಾಬ್ ಆಯ್ಕೆಮಾಡಿ, ಯಾರಿಗೆ ಪ್ರವೇಶ ಇದೆ ಎಂದು ನೋಡಿ, ನಂತರ ಚೆಕ್‌ಬಾಕ್ಸ್‌ನಲ್ಲಿ ಅನುಮತಿ ಕೊಡಿ.",
    landingPage: "ಲ್ಯಾಂಡಿಂಗ್ ಪುಟ",
    navLeaders: "ಮುಖಂಡರು",
    navTourSchedules: "ಪ್ರವಾಸ ಕಾರ್ಯಕ್ರಮ",
    tourPageTitle: "ಮಾನ್ಯ ಶಾಸಕರ ಪ್ರವಾಸ ಕಾರ್ಯಕ್ರಮ",
    addTourDay: "ದಿನ ಸೇರಿಸಿ",
    editTourDay: "ದಿನದ ವೇಳಾಪಟ್ಟಿ ಸಂಪಾದಿಸಿ",
    tourDate: "ದಿನಾಂಕ",
    tourDayImage: "ದೈನಂದಿನ ವೇಳಾಪಟ್ಟಿ ಚಿತ್ರ",
    tourFallbackImage: "ಡೀಫಾಲ್ಟ್ ಚಿತ್ರ",
    tourDateRequired: "ದಿನಾಂಕ ಅಗತ್ಯವಿದೆ",
    tourImageRequired: "ವೇಳಾಪಟ್ಟಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    tourDateExists: "ಈ ದಿನಾಂಕಕ್ಕೆ ವೇಳಾಪಟ್ಟಿ ಇದೆ. Edit ಬಳಸಿ.",
    tourDraftSaved: "ಡ್ರಾಫ್ಟ್ ಉಳಿಸಲಾಗಿದೆ — Sync ಒತ್ತಿ",
    tourSynced: "ಲ್ಯಾಂಡಿಂಗ್‌ಗೆ Sync ಆಯಿತು",
    tourRemoveConfirm: "ಈ ದಿನದ ವೇಳಾಪಟ್ಟಿ ತೆಗೆಯುವುದೇ?",
    tourNoDays: "ದಿನದ ವೇಳಾಪಟ್ಟಿ ಇಲ್ಲ",
    tourDayHint: "ಈ ದಿನಾಂಕಕ್ಕೆ ವೇಳಾಪಟ್ಟಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    tourPageDesc: "ದಿನವಾರು schedule sheets. Sync ನಂತರ public calendar.",
    tourCalendarHint:
      "ಇಂದು ಮತ್ತು ಮುಂದಿನ ದಿನಗಳಿಗೆ ಅಪ್‌ಲೋಡ್. ಫೈಲ್ ಇದ್ದರೆ ನೋಡಿ. ಹಿಂದಿನ ಖಾಲಿ ದಿನಗಳು ಲಾಕ್.",
    tourHasFile: "ಅಪ್‌ಲೋಡ್ — ನೋಡಲು ಕ್ಲಿಕ್",
    tourToday: "ಇಂದು",
    tourClickEmpty: "ಇಂದು/ಮುಂದಿನ ಖಾಲಿ ದಿನಕ್ಕೆ ಅಪ್‌ಲೋಡ್",
    tourViewDay: "ಈ ದಿನದ ವೇಳಾಪಟ್ಟಿ",
    tourUploadDay: "ವೇಳಾಪಟ್ಟಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್",
    tourUploadOnlyHint: "ಚಿತ್ರ ಮಾತ್ರ ಅಪ್‌ಲೋಡ್. ಸ್ವಯಂ publish ಆಗುತ್ತದೆ.",
    tourUploadPublish: "ಅಪ್‌ಲೋಡ್ & publish",
    tourUsesRecent: "ಇತ್ತೀಚಿನ sheet",
    tourPastNoUpload: "ಇಂದು ಮತ್ತು ಮುಂದಿನ ದಿನಗಳಿಗೆ ಮಾತ್ರ ಅಪ್‌ಲೋಡ್",
    tourUploadFromToday: "ಅಪ್‌ಲೋಡ್: ಇಂದು & ಮುಂದಿನ ದಿನಗಳು ಮಾತ್ರ",
    remove: "ತೆಗೆದುಹಾಕಿ",
    addLeader: "ಮುಖಂಡರನ್ನು ಸೇರಿಸಿ",
    editLeader: "ಮುಖಂಡರನ್ನು ಸಂಪಾದಿಸಿ",
    leaderNameRequired: "ಹೆಸರು ಅಗತ್ಯವಿದೆ",
    leaderPhoneRequired: "ಫೋನ್ ಅಥವಾ ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ",
    landingPageDesc: "ಪಠ್ಯ, ಚಿತ್ರ, ಬಣ್ಣ ಸಂಪಾದಿಸಿ. Sync ಮಾಡಿ ಸಾರ್ವಜನಿಕ ಪುಟಕ್ಕೆ ಕಳುಹಿಸಿ.",
    landingSave: "ಉಳಿಸಿ",
    landingSync: "Sync to landing",
    landingSynced: "Synced",
    landingReset: "ಡೀಫಾಲ್ಟ್‌ಗೆ ಮರುಹೊಂದಿಸಿ",
    landingResetDone: "Reset done",
    landingOpen: "ಲ್ಯಾಂಡಿಂಗ್ ತೆರೆಯಿರಿ",
    landingOpenPreview: "Open preview",
    landingPreviewOpened: "Preview opened",
    landingShowPreview: "Show preview",
    landingHidePreview: "Hide preview",
    landingPreviewHint: "Preview updates as you edit. Sync to update public page.",
    landingSaved: "ಲ್ಯಾಂಡಿಂಗ್ ಪುಟ ಉಳಿಸಲಾಗಿದೆ",
    landingResetConfirm: "ಎಲ್ಲಾ ಲ್ಯಾಂಡಿಂಗ್ ವಿಷಯವನ್ನು ಡೀಫಾಲ್ಟ್‌ಗೆ ಮರುಹೊಂದಿಸುವುದೇ?",
    adminSidebarTitle: "ನಿರ್ವಾಹಕ ಪ್ಯಾನೆಲ್",
    adminSidebarHint: "ಎಲ್ಲಾ ಮಾಡ್ಯೂಲ್‌ಗಳು · ಒಂದೇ ಸ್ಥಳ",
    sidebarCollapse: "ಮೆನು ಮುಚ್ಚಿ",
    sidebarExpand: "ಮೆನು ತೆರೆಯಿರಿ",
    navDemands: "ಬೇಡಿಕೆಗಳು",
    navComplaints: "ದೂರುಗಳು",
    complaintsPageDesc: "Public landing complaint submissions inbox",
    navAssembly:  "ಅಧಿವೇಶನ ಪ್ರಶ್ನೋತ್ತರ",
    accessStaffList: "ಸಿಬ್ಬಂದಿ",
    accessAddStaff: "ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ",
    accessNoStaff: "ಸಿಬ್ಬಂದಿ ಇಲ್ಲ. ಹೊಸದನ್ನು ಸೇರಿಸಿ.",
    accessNameEn: "ಹೆಸರು (EN)",
    accessNameKn: "ಹೆಸರು (KN)",
    accessNameMain: "ಹೆಸರು",
    accessNameKnOptional: "ಕನ್ನಡ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    accessNameLangHint:
      "ಹೆಸರು ಇಂಗ್ಲಿಷ್ ಮತ್ತು ಕನ್ನಡ ಎರಡಕ್ಕೂ ಬಳಕೆ. ಬೇರೆ ಕನ್ನಡ ಬೇಕಿದ್ದರೆ ಮಾತ್ರ ಕನ್ನಡ ಹೆಸರು ಭರ್ತಿ ಮಾಡಿ.",
    accessFillKannada: "ಹೆಸರಿನಿಂದ ಕನ್ನಡ ಭರ್ತಿ",
    accessNeedOnePerm: "ಉಳಿಸುವ ಮೊದಲು ಕನಿಷ್ಠ ಒಂದು ಅನುಮತಿ ಟಿಕ್ ಮಾಡಿ.",
    accessUsersOnPortal: "ಪ್ರವೇಶವಿರುವ ಬಳಕೆದಾರರು",
    accessNoUsersOnPortal: "ಈ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಯಾರೂ ಇಲ್ಲ. ಮೇಲೆ ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ.",
    accessAddToPortalHint: "ಈ ಪೋರ್ಟಲ್‌ಗೆ ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ (View ಡೀಫಾಲ್ಟ್ ಆನ್).",
    accessAddToPortal: "ಈ ಪೋರ್ಟಲ್‌ಗೆ ಸೇರಿಸಿ",
    accessStaffCol: "ಸಿಬ್ಬಂದಿ",
    accessRemoveFromPortal: "ಈ ಪೋರ್ಟಲ್‌ನಿಂದ ತೆಗೆದುಹಾಕುವುದೇ?",
    accessRemovedFromPortal: "ಈ ಪೋರ್ಟಲ್‌ನಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.",
    accessStaffAdded: "ಸಿಬ್ಬಂದಿಯನ್ನು ಈ ಪೋರ್ಟಲ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ.",
    accessProfileSaved: "ಹೆಸರು ಮತ್ತು ಫೋನ್ ನವೀಕರಿಸಲಾಗಿದೆ.",
    accessPhoneTaken: "ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ಬೇರೆ ಸಿಬ್ಬಂದಿಗೆ ಇದೆ.",
    accessNameRequired: "ಹೆಸರು ನಮೂದಿಸಿ.",
    accessPortalRights: "ಅನುಮತಿಗಳನ್ನು ಹೊಂದಿಸಿ",
    accessToggleHint: "ಅನುಮತಿಗೆ ಬಾಕ್ಸ್ ಟಿಕ್ ಮಾಡಿ.",
    accessSummaryTitle: "ಈಗ ಕೊಟ್ಟಿರುವ ಪ್ರವೇಶ",
    accessAllowed: "ಅನುಮತಿ",
    accessDenied: "ಆಫ್",
    accessNoneGranted: "ಇನ್ನೂ ಪ್ರವೇಶವಿಲ್ಲ",
    accessNoPortalAccess: "ಈ ಪೋರ್ಟಲ್‌ಗೆ ಪ್ರವೇಶವಿಲ್ಲ",
    accessGiveAll: "ಎಲ್ಲಾ ಕೊಡಿ",
    accessClearAll: "ಎಲ್ಲಾ ತೆರವು",
    accessSaved: "ಪ್ರವೇಶ ಉಳಿಸಲಾಗಿದೆ.",
    accessDeleted: "ಸಿಬ್ಬಂದಿ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.",
    accessConfirmDelete: "ಈ ಸಿಬ್ಬಂದಿ ಪ್ರವೇಶವನ್ನು ತೆಗೆದುಹಾಕುವುದೇ?",
    accessInvalidPhone: "ಮಾನ್ಯವಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ನಮೂದಿಸಿ",
    deptUpload: "ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    deptUploadHint: "PDF, ಚಿತ್ರ ಅಥವಾ ದಾಖಲೆ — ಪ್ರತಿ ಫೈಲ್ ಗರಿಷ್ಠ 2.5 MB",
    deptTitleOptional: "ಶೀರ್ಷಿಕೆ (ಐಚ್ಛಿಕ)",
    deptTitlePlaceholder: "ಈ ಫೈಲ್‌ಗೆ ಸಂಕ್ಷಿಪ್ತ ಹೆಸರು",
    deptEmpty: "ಈ ವರ್ಗದಲ್ಲಿ ದಾಖಲೆಗಳಿಲ್ಲ. ಹೊಸದನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    deptConfirmDelete: "ಈ ದಾಖಲೆಯನ್ನು ಆರ್ಕೈವ್ ಮಾಡುವುದೇ? ಇದು ಮರೆಮಾಡಲಾಗುತ್ತದೆ, ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲಾಗುವುದಿಲ್ಲ.",
    archive: "ಆರ್ಕೈವ್",
    archiveConfirm: "ಈ ದಾಖಲೆಯನ್ನು ಆರ್ಕೈವ್ ಮಾಡುವುದೇ? ಇದು ಮರೆಮಾಡಲಾಗುತ್ತದೆ, ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲಾಗುವುದಿಲ್ಲ.",
    actions: "ಕ್ರಿಯೆಗಳು",
    deptOpen: "ತೆರೆಯಿರಿ",
    deptFileTooLarge: "ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದು (ಗರಿಷ್ಠ 2.5 MB).",
    deptUploadFailed: "ಫೈಲ್ ಓದಲಾಗಲಿಲ್ಲ. ಬೇರೆಯದನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
    deptUploaded: "ಅಪ್‌ಲೋಡ್ ಆಯಿತು",
    deptSelectFiles: "ಫೈಲ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    deptUploading: "ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    deptDropHere: "ಫೈಲ್‌ಗಳನ್ನು ಇಲ್ಲಿ ಬಿಡಿ",
    deptDropOrClick: "ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ ಆಯ್ಕೆಮಾಡಲು",
    deptDragging: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಬಿಡಿ",
    deptSearchPlaceholder: "ಶೀರ್ಷಿಕೆ, ಫೈಲ್ ಹೆಸರು, ವರ್ಗದಿಂದ ಹುಡುಕಿ…",
    deptSearchHint: "ಎಲ್ಲಾ ಇಲಾಖಾ ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಲು ಟೈಪ್ ಮಾಡಿ…",
    deptStatus: "ಸ್ಥಿತಿ",
    deptEGeneratedId: "ಇ-ಜನರೇಟೆಡ್ ಐಡಿ",
    deptEGeneratedIdPlaceholder: "ಇ-ಜನರೇಟೆಡ್ ಐಡಿ ನಮೂದಿಸಿ",
    deptEGeneratedIdRequired: "ಅನುಸರಣೆಗೆ ಇ-ಜನರೇಟೆಡ್ ಐಡಿ ಅಗತ್ಯವಿದೆ.",
    logout: "ಲಾಗ್ ಔಟ್",
    themeToggle: "ಡಾರ್ಕ್ / ಲೈಟ್ ಥೀಮ್ ಬದಲಿಸಿ",
    themeLight: "ಲೈಟ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ",
    themeDark: "ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ",
    logoutConfirmTitle: "ಲಾಗ್ ಔಟ್ ಮಾಡುವುದೇ?",
    logoutConfirmMessage: "ನೀವು ಪೋರ್ಟಲ್‌ನಿಂದ ಲಾಗ್ ಔಟ್ ಆಗಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?",
    logoutConfirmYes: "ಹೌದು, ಲಾಗ್ ಔಟ್",
    logoutConfirmNo: "ಲಾಗ್ ಇನ್‌ನಲ್ಲೇ ಇರಿ",
    welcome: "ಸ್ವಾಗತ",
    adminHomeTitle: "ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    adminHomeDesc: "ಕಚೇರಿ ಸಂಪೂರ್ಣ ಅವಲೋಕನ — ಕಾಮಗಾರಿ, ದಾಖಲೆಗಳು ಮತ್ತು ಸಿಬ್ಬಂದಿ ಪ್ರವೇಶ. ಮಾಡ್ಯೂಲ್ ತೆರೆಯಲು ಸೈಡ್‌ಬಾರ್ ಬಳಸಿ.",
    adminModules: "ಕಚೇರಿ ಮಾಡ್ಯೂಲ್‌ಗಳು",
    adminChartsSection: "ವಿಶ್ಲೇಷಣೆ",
    adminChartNoData: "ಈ ವರ್ಷಕ್ಕೆ ಡೇಟಾ ಇಲ್ಲ",
    adminChartInteractiveHint: "ಆರು ವಿಶ್ಲೇಷಣೆಗಳು · ಸಾಲಿಗೆ 2 · ಪ್ರತಿಯೊಂದಕ್ಕೂ ವರ್ಷ ಫಿಲ್ಟರ್.",
    adminChartYear: "ವರ್ಷ",
    adminChartAllYears: "ಎಲ್ಲಾ ವರ್ಷಗಳು",
    adminChartTitleWorksByGp: "ಗ್ರಾಮ ಪಂಚಾಯತ್ ಪ್ರಕಾರ ಕಾಮಗಾರಿಗಳು",
    adminChartHintWorksByGp: "ಪ್ರತಿ ಜಿಪಿಯಲ್ಲಿ ಎಷ್ಟು ಕಾಮಗಾರಿಗಳಿವೆ ಎಂದು ತೋರಿಸುತ್ತದೆ.",
    adminChartTitleStatus: "ಸ್ಥಿತಿ ಪ್ರಕಾರ ಕಾಮಗಾರಿಗಳು",
    adminChartHintStatus: "ಚಾಲ್ತಿಯಲ್ಲಿರುವ ಮತ್ತು ಪೂರ್ಣಗೊಂಡ ಕಾಮಗಾರಿಗಳ ಪಾಲು.",
    adminChartTitleAmountTrend: "ಮಂಜೂರಾತಿ ಮೊತ್ತದ ಪ್ರವೃತ್ತಿ",
    adminChartHintAmountTrend: "ತಿಂಗಳು ವಾರು ಮಂಜೂರಾದ ಮೊತ್ತದ ಲೈನ್.",
    adminChartTitleByYojane: "ಯೋಜನೆ ಪ್ರಕಾರ ಮೊತ್ತ",
    adminChartHintByYojane: "ಯಾವ ಯೋಜನೆಗೆ ಹೆಚ್ಚು ನಿಧಿ ಹೋಗಿದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ.",
    adminChartTitleProgress: "ತಿಂಗಳು ವಾರು ಪ್ರಗತಿ",
    adminChartHintProgress: "ಚಾಲ್ತಿ ಮತ್ತು ಪೂರ್ಣಗೊಂಡ ಕಾಮಗಾರಿಗಳನ್ನು ತಿಂಗಳು ವಾರು ತೋರಿಸುತ್ತದೆ.",
    adminChartTitleCombo: "ಕಾಮಗಾರಿ ಸಂಖ್ಯೆ ಮತ್ತು ಮೊತ್ತ",
    adminChartHintCombo: "ಬಾರ್ = ಕಾಮಗಾರಿ ಸಂಖ್ಯೆ · ಲೈನ್ = ಮಂಜೂರಾದ ಮೊತ್ತ.",
    adminChartTypeColumn: "ಕಾಲಮ್",
    adminChartTypePie: "ಪೈ",
    adminChartTypeLine: "ಲೈನ್",
    adminChartTypeBar: "ಬಾರ್",
    adminChartTypeArea: "ಏರಿಯಾ",
    adminChartTypeCombo: "ಕಾಲಮ್ + ಲೈನ್",
    adminStatDocs: "ದಾಖಲೆಗಳು",
    adminStatStaff: "ಸಿಬ್ಬಂದಿ",
    adminStatPopulation: "ಒಟ್ಟು ಜನಸಂಖ್ಯೆ",
    adminStatGps: "ಗ್ರಾಮ ಪಂಚಾಯತ್‌ಗಳು",
    adminStatVillages: "ಗ್ರಾಮಗಳು",
    adminModDevDesc: "ಗ್ರಾಮ ಪಂಚಾಯತ್ ಕಾಮಗಾರಿ, ಮೊತ್ತ, ಫೋಟೋ ಮತ್ತು ವರದಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    openDevelopment: "ಕಾಮಗಾರಿಗಳು ತೆರೆಯಿರಿ",
    gp: "ಗ್ರಾಮ ಪಂಚಾಯತ್",
    village: "ಗ್ರಾಮ",
    selectGp: "ಗ್ರಾಮ ಪಂಚಾಯತ್ ಆಯ್ಕೆಮಾಡಿ",
    selectVillage: "ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ",
    addRecord: "ಕಾಮಗಾರಿ ಸೇರಿಸಿ",
    editRecord: "ಕಾಮಗಾರಿ ಸಂಪಾದಿಸಿ",
    colName: "ಕಾಮಗಾರಿ ಹೆಸರು",
    colAmount: "ಮಂಜೂರಾದ ಮೊತ್ತ",
    colImages: "ಕಾಮಗಾರಿ ಚಿತ್ರಗಳು",
    colYojane: "ಯೋಜನೆ",
    colDescription: "ವಿವರಣೆ",
    colActions: "ಕ್ರಿಯೆಗಳು",
    edit: "ಸಂಪಾದಿಸಿ",
    delete: "ಅಳಿಸಿ",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದು",
    confirmDelete: "ಈ ಕಾಮಗಾರಿ ದಾಖಲೆಯನ್ನು ಅಳಿಸುವುದೇ?",
    noRows: "ಈ ಗ್ರಾಮಕ್ಕೆ ಕಾಮಗಾರಿಗಳಿಲ್ಲ. ಹೊಸದನ್ನು ಸೇರಿಸಿ.",
    noRowsFiltered: "ಈ ಫಿಲ್ಟರ್‌ಗೆ ಹೊಂದುವ ಕಾಮಗಾರಿಗಳಿಲ್ಲ. ಸ್ಥಿತಿ ಬದಲಾಯಿಸಿ ಅಥವಾ ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ.",
    pickFilters: "ದಾಖಲೆಗಳನ್ನು ನೋಡಲು ಗ್ರಾಮ ಪಂಚಾಯತ್ ಮತ್ತು ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ.",
    pickVillageHint: "ಈ ಗ್ರಾಮ ಪಂಚಾಯತ್‌ನ ಕಾಮಗಾರಿಗಳನ್ನು ನೋಡಲು ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ.",
    clearFilters: "ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ",
    filterStatus: "ಸ್ಥಿತಿ",
    filterStatusAll: "ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು",
    sortBy: "ವಿಂಗಡಿಸಿ",
    sortNewest: "ಹೊಸದು ಮೊದಲು",
    sortOldest: "ಹಳೆಯದು ಮೊದಲು",
    sortAmountHigh: "ಮೊತ್ತ — ಹೆಚ್ಚಿನದು ಮೊದಲು",
    sortAmountLow: "ಮೊತ್ತ — ಕಡಿಮೆ ಮೊದಲು",
    sortName: "ಹೆಸರು ಅ–ಆ",
    emptyAddCta: "ಮೊದಲ ಕಾಮಗಾರಿ ಸೇರಿಸಿ",
    namePlaceholder: "ಉದಾ. ರಸ್ತೆ ದುರಸ್ತಿ",
    amountPlaceholder: "ಮೊತ್ತ (ರೂ)",
    yojanePlaceholder: "ಉದಾ. ಮನರೇಗಾ",
    descriptionPlaceholder: "ಈ ಕಾಮಗಾರಿಯ ಸಂಕ್ಷಿಪ್ತ ವಿವರಣೆ",
    uploadImages: "ಫೋಟೋ ಮತ್ತು ವೀಡಿಯೋ ಅಪ್‌ಲೋಡ್",
    uploadMediaHint: "ಒಂದು ಅಥವಾ ಹೆಚ್ಚು ಫೋಟೋ / ವೀಡಿಯೋ ಸೇರಿಸಬಹುದು",
    removeImage: "ತೆಗೆದುಹಾಕಿ",
    mediaPhotos: "ಫೋಟೋಗಳು",
    mediaVideos: "ವೀಡಿಯೋಗಳು",
    colMedia: "ಫೋಟೋ ಮತ್ತು ವೀಡಿಯೋ",
    videoLabel: "ವೀಡಿಯೋ",
    quickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    download: "ಡೌನ್‌ಲೋಡ್",
    downloadTitle: "ಕಾಮಗಾರಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    downloadScope: "ಏನನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಬೇಕು",
    downloadFormat: "ಫೈಲ್ ಫಾರ್ಮ್ಯಾಟ್",
    downloadNow: "ಈಗ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    scopeAll: "ಎಲ್ಲಾ ಕಾಮಗಾರಿಗಳು",
    scopeGp: "ಒಂದು ಗ್ರಾಮ ಪಂಚಾಯತ್",
    scopeVillage: "ಒಂದು ಗ್ರಾಮ",
    searchPlaceholder: "ಹೆಸರು, ಯೋಜನೆ, ವಿವರಣೆಯಿಂದ ಹುಡುಕಿ…",
    searchNoResults: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಕಾಮಗಾರಿಗಳಿಲ್ಲ.",
    search: "ಹುಡುಕಿ",
    searchHint: "ಎಲ್ಲಾ ಕಾಮಗಾರಿಗಳನ್ನು ಹುಡುಕಲು ಟೈಪ್ ಮಾಡಿ…",
    voiceTapToSpeak: "ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    voiceListening: "ಕೇಳುತ್ತಿದೆ… ನಿಲ್ಲಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    voiceListeningShort: "ಕೇಳುತ್ತಿದೆ…",
    voiceUnsupported: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಹುಡುಕಾಟ ಬೆಂಬಲಿತವಲ್ಲ",
    voiceMicDenied: "ಧ್ವನಿ ಹುಡುಕಾಟಕ್ಕೆ ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ಬೇಕು",
    voiceMicDeniedTitle: "ಮೈಕ್ರೋಫೋನ್ ಆನ್ ಮಾಡಿ",
    voiceMicDeniedBody:
      "ಈ ಬ್ರೌಸರ್ ಮೈಕ್ರೋಫೋನ್ ಅನ್ನು ನಿರ್ಬಂಧಿಸಿದೆ. ಈ ಸೈಟ್‌ಗೆ ಮೈಕ್ ಅನುಮತಿ ನೀಡಿ, ನಂತರ ಮತ್ತೆ ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ.",
    voiceMicMissingTitle: "ಮೈಕ್ರೋಫೋನ್ ಸಿಗಲಿಲ್ಲ",
    voiceMicMissingBody:
      "ಮೈಕ್ರೋಫೋನ್ ಸಂಪರ್ಕಿಸಿ (ಅಥವಾ ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್‌ನಲ್ಲಿ ಆನ್ ಮಾಡಿ), ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    voiceMicStep1: "ಅಡ್ರೆಸ್ ಬಾರ್ ಬಳಿ ಲಾಕ್ / ಸೈಟ್ ಮಾಹಿತಿ ಐಕಾನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    voiceMicStep2: "Microphone ಅನ್ನು Allow ಮಾಡಿ",
    voiceMicStep3: "ಪುಟವನ್ನು ರಿಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಮತ್ತೆ ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ",
    voiceMicGotIt: "ಸರಿ",
    voiceUseChrome: "ಧ್ವನಿ ಹುಡುಕಾಟಕ್ಕೆ Chrome ಅಥವಾ Edge ಬಳಸಿ.",
    globalSearchPlaceholder: "ಕಾಮಗಾರಿ, ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ…",
    globalSearchHint: "ನಿಮಗೆ ಪ್ರವೇಶವಿರುವ ಮಾಡ್ಯೂಲ್‌ಗಳಲ್ಲಿ ಹುಡುಕಿ…",
    previewTitle: "ಪೂರ್ವವೀಕ್ಷಣೆ",
    previewSummary: "ಸಾರಾಂಶ",
    previewRecords: "ದಾಖಲೆಗಳು",
    previewEmpty: "ದಾಖಲೆಗಳನ್ನು ಇಲ್ಲಿ ನೋಡಲು ವ್ಯಾಪ್ತಿ ಆಯ್ಕೆಮಾಡಿ.",
    dateRange: "ದಿನಾಂಕ ವ್ಯಾಪ್ತಿ",
    dateFrom: "ಇಂದಿನಿಂದ",
    dateTo: "ಇಲ್ಲಿಯವರೆಗೆ",
    dateHint: "ಐಚ್ಛಿಕ — ಕಾಮಗಾರಿ ಪ್ರಾರಂಭ ದಿನಾಂಕದಿಂದ ಫಿಲ್ಟರ್",
    chartsTitle: "ಅವಲೋಕನ",
    chartTotalWorks: "ಒಟ್ಟು ಕಾಮಗಾರಿಗಳು",
    chartTotalAmount: "ಒಟ್ಟು ಮೊತ್ತ",
    chartOngoing: "ಚಾಲ್ತಿಯಲ್ಲಿದೆ",
    chartCompleted: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    chartByStatus: "ಸ್ಥಿತಿ ಪ್ರಕಾರ ಕಾಮಗಾರಿಗಳು",
    chartByYojane: "ಯೋಜನೆ ಪ್ರಕಾರ ಮೊತ್ತ",
    chartPieStatus: "ಸ್ಥಿತಿ ಪೈ ಚಾರ್ಟ್",
    chartBarYojane: "ಬಾರ್ ಚಾರ್ಟ್ — ಯೋಜನೆ ಪ್ರಕಾರ ಮೊತ್ತ",
    chartLineTrend: "ಲೈನ್ ಚಾರ್ಟ್ — ಮಂಜೂರಾತಿ ಪ್ರವೃತ್ತಿ",
    chartLineHint: "ಕಾಮಗಾರಿ ಪ್ರಾರಂಭ ತಿಂಗಳ ಆಧಾರದ ಮೇಲೆ",
    chartBarCount: "ಬಾರ್ ಚಾರ್ಟ್ — ಯೋಜನೆ ಪ್ರಕಾರ ಸಂಖ್ಯೆ",
    close: "ಮುಚ್ಚಿ",
    viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಲು ಒತ್ತಿ",
    detailsTitle: "ಕಾಮಗಾರಿ ವಿವರಗಳು",
    colStatus: "ಸ್ಥಿತಿ",
    colBeneficiaries: "ಫಲಾನುಭವಿಗಳು",
    colDepartment: "ಇಲಾಖೆ",
    colStartDate: "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
    colLocation: "ಸ್ಥಳ",
    colMoreDetails: "ಕಾಮಗಾರಿ ವಿವರ",
    gpLabel: "ಗ್ರಾಮ ಪಂಚಾಯತ್",
    villageLabel: "ಗ್ರಾಮ",
    bedkePageDesc: "ಬೇಡಿಕೆಗಳನ್ನು ನೋಡಲು ಅಥವಾ ಸೇರಿಸಲು ಗ್ರಾಮ ಪಂಚಾಯತ್ ಮತ್ತು ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ.",
    bedkePickGpHint: "ಇರುವ ಬೇಡಿಕೆಗಳನ್ನು ನೋಡಲು ಗ್ರಾಮ ಪಂಚಾಯತ್ ಮತ್ತು ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ.",
    bedkeTabCivil: "ಸಿವಿಲ್ ವಿಧಾನ",
    bedkeTabPersonal: "ವೈಯಕ್ತಿಕ ವಿಧಾನ",
    bedkeNoNeeds: "ಈ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ಈ ಗ್ರಾಮಕ್ಕೆ ಬೇಡಿಕೆಗಳಿಲ್ಲ.",
    bedkeAdd: "ಬೇಡಿಕೆ ಸೇರಿಸಿ",
    bedkeName: "ಹೆಸರು",
    bedkeNamePlaceholder: "ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ",
    bedkeNameRequired: "ಹೆಸರು ನಮೂದಿಸಿ.",
    bedkeApproach: "ವಿಧಾನ",
    bedkeSubject: "ವಿಷಯ",
    bedkeSubjectPlaceholder: "ಬೇಡಿಕೆ / ವಿನಂತಿಯನ್ನು ವಿವರಿಸಿ",
    bedkeSubjectRequired: "ವಿಷಯ ನಮೂದಿಸಿ.",
    bedkeSelectVillageFirst: "ಮೊದಲು ಗ್ರಾಮ ಪಂಚಾಯತ್ ಮತ್ತು ಗ್ರಾಮ ಆಯ್ಕೆಮಾಡಿ.",
    bedkeStatus: "ಸ್ಥಿತಿ",
    bedkePending: "ಬಾಕಿ",
    bedkeInProgress: "In progress",
    bedkeCompleted: "Completed",
    bedkeRejected: "Rejected",
    bedkeEdit: "Edit demand",
    bedkeConfirmSave: "Confirm and save",
    bedkeDate: "ದಿನಾಂಕ",
    bedkePreview: "ಪೂರ್ವವೀಕ್ಷಣೆ",
    bedkePreviewTitle: "ಬೇಡಿಕೆ ಪೂರ್ವವೀಕ್ಷಣೆ",
    bedkePreviewHint: "ಕೆಳಗಿನ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ನಂತರ ಬಾಕಿ ಸ್ಥಿತಿಯಲ್ಲಿ ಉಳಿಸಲು ದೃಢೀಕರಿಸಿ.",
    bedkeBackEdit: "ಸಂಪಾದನೆಗೆ ಹಿಂದಿರುಗಿ",
    bedkeConfirmSubmit: "ದೃಢೀಕರಿಸಿ ಮತ್ತು ಸಲ್ಲಿಸಿ",
    bedkeSearchPlaceholder: "ಹೆಸರು, ವಿಷಯ, ಗ್ರಾಮ ಪಂಚಾಯತ್, ಗ್ರಾಮ…",
    bedkeSearchHint: "ಎಲ್ಲಾ ಬೇಡಿಕೆಗಳನ್ನು ಹುಡುಕಲು ಟೈಪ್ ಮಾಡಿ…",
    bedkeSearchNoResults: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಬೇಡಿಕೆಗಳಿಲ್ಲ.",
    bedkeDownloadTitle: "ಬೇಡಿಕೆಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    aqPageDesc:
      "ಶಾಸಕರು ಅಥವಾ ಇತರ ಪಕ್ಷಗಳು ಕೇಳಿದ ಅಧಿವೇಶನ ಪ್ರಶ್ನೆಗಳು, ಉತ್ತರಗಳು ಮತ್ತು ಫೈಲ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    aqTabAll: "ಎಲ್ಲಾ",
    aqTabMla: "ಶಾಸಕರು ಕೇಳಿದ್ದು",
    aqTabOther: "ಇತರರು ಕೇಳಿದ್ದು",
    aqAdd: "ಪ್ರಶ್ನೋತ್ತರ ಸೇರಿಸಿ",
    aqFormHint: "ಪ್ರಶ್ನೆ, ಯಾರು ಕೇಳಿದರು, ಉತ್ತರ (ಇದ್ದರೆ) ಮತ್ತು ಫೈಲ್‌ಗಳನ್ನು ನಮೂದಿಸಿ.",
    aqQuestionNo: "ಪ್ರಶ್ನೆ ಸಂಖ್ಯೆ",
    aqSessionDate: "ಅಧಿವೇಶನ ದಿನಾಂಕ",
    aqSessionLabel: "ಅಧಿವೇಶನ",
    aqSessionPlaceholder: "ಉದಾ: ಮಳೆಗಾಲದ ಅಧಿವೇಶನ 2026",
    aqAskedBy: "ಯಾರು ಕೇಳಿದರು",
    aqAskedByName: "ಹೆಸರು",
    aqAskedByNamePlaceholder: "ಕೇಳಿದ ಸದಸ್ಯರ ಹೆಸರು",
    aqAskedByNameRequired: "ಕೇಳಿದವರ ಹೆಸರು ನಮೂದಿಸಿ.",
    aqParty: "ಪಕ್ಷ",
    aqPartyPlaceholder: "ಪಕ್ಷ / ಗುಂಪಿನ ಹೆಸರು",
    aqPartyRequired: "ಪಕ್ಷದ ಹೆಸರು ನಮೂದಿಸಿ.",
    aqQuestion: "ಪ್ರಶ್ನೆ",
    aqQuestionPlaceholder: "ಅಧಿವೇಶನದ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ…",
    aqQuestionRequired: "ಪ್ರಶ್ನೆಯನ್ನು ನಮೂದಿಸಿ.",
    aqAnswer: "ಉತ್ತರ",
    aqAnswerPlaceholder: "ಉತ್ತರ / ಇಲಾಖಾ ಪ್ರತ್ಯುತ್ತರ (ಐಚ್ಛಿಕ)…",
    aqNoAnswerYet: "ಇನ್ನೂ ಉತ್ತರ ಸೇರಿಸಿಲ್ಲ.",
    aqStatus: "ಸ್ಥಿತಿ",
    aqStatusPending: "ಬಾಕಿ",
    aqStatusAnswered: "ಉತ್ತರಿಸಲಾಗಿದೆ",
    aqAttachFiles: "ಫೈಲ್‌ಗಳನ್ನು ಲಗತ್ತಿಸಿ",
    aqFiles: "ಫೈಲ್‌ಗಳು",
    aqNoFiles: "ಯಾವುದೇ ಫೈಲ್ ಲಗತ್ತಿಸಿಲ್ಲ.",
    aqView: "ನೋಡಿ",
    aqSave: "ಪ್ರಶ್ನೋತ್ತರ ಉಳಿಸಿ",
    aqEmpty: "ಈ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ಪ್ರಶ್ನೋತ್ತರಗಳಿಲ್ಲ. ಹೊಸದನ್ನು ಸೇರಿಸಿ.",
    aqRecords: "ದಾಖಲೆಗಳು",
    aqConfirmDelete: "ಈ ಅಧಿವೇಶನ ಪ್ರಶ್ನೋತ್ತರವನ್ನು ಅಳಿಸುವುದೇ?",
    aqSearchPlaceholder: "ಪ್ರಶ್ನೆ, ಉತ್ತರ, ಹೆಸರು, ಪಕ್ಷದಿಂದ ಹುಡುಕಿ…",
    aqSearchHint: "ಎಲ್ಲಾ ಅಧಿವೇಶನ ಪ್ರಶ್ನೋತ್ತರಗಳನ್ನು ಹುಡುಕಲು ಟೈಪ್ ಮಾಡಿ…",
    aqSearchNoResults: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಪ್ರಶ್ನೋತ್ತರಗಳಿಲ್ಲ.",


  },
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState("kn");

  useEffect(() => {
    const saved = localStorage.getItem("mla_lang");
    if (saved === "en" || saved === "kn") setLangState(saved);
  }, []);

  const setLang = (next) => {
    setLangState(next);
    if (typeof window !== "undefined") {
      localStorage.setItem("mla_lang", next);
    }
  };

  const value = {
    lang,
    setLang,
    t: dashboardCopy[lang] || dashboardCopy.kn,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageToggle({ className = "" }) {
  const { lang, setLang } = useLanguage();
  return (
    <div
      className={`flex items-center gap-1 bg-[#1e2223]/80 p-1 rounded-full border border-white/20 h-fit ${className}`}
    >
      <button
        type="button"
        onClick={() => setLang("en")}
        className={`px-2.5 py-1 text-xs font-black rounded-full transition-all duration-300 ${
          lang === "en"
            ? "bg-[#367AF1] text-white shadow-md"
            : "text-white/60 hover:text-white"
        }`}
      >
        EN
      </button>
      <button
        type="button"
        onClick={() => setLang("kn")}
        className={`px-2.5 py-1 text-xs font-black rounded-full transition-all duration-300 ${
          lang === "kn"
            ? "bg-[#367AF1] text-white shadow-md"
            : "text-white/60 hover:text-white"
        }`}
      >
        ಕನ್ನಡ
      </button>
    </div>
  );
}
